### ISSUE TITLE
OCPI data model correlation

### ISSUE THREAD

**Issue by sarahgudc** [smart-data-models/dataModel.Transportation#10]
I am working with data from Charge Point Operators that is typically delivered through their APIs following the OCPI model - a widely adopted standard for EV charging data in the UK (and wider).
I want to convert the OCPI data into NGSI-LD and have been looking at how this smart data model would fit my needs. Please can you help clarify a few things about this data model:

- What real world object does this model represent? Is it representing a location where there are a collection of charge point devices (each with their own EVSEs and associated connectors) - like a petrol station or garage? Is it representing a single charge point device (with its own EVSEs and associated connectors)?

- What is the charging topology that this model represents? In OCPI the topology is as follows: 
• Connector is a specific socket or cable available for the EV to make use of.
• EVSE is the part that controls the power supply to a single EV in a single session. An EVSE may provide multiple
connectors but only one of these can be active at the same time.
• Location is a group of one or more EVSEs that belong together geographically or spatially.
See attached diagram for more visual overview.

<img width="703" alt="Screenshot 2021-03-12 at 10 43 57" src="https://user-images.githubusercontent.com/78149717/110929488-e68a9a00-831f-11eb-9c86-36f353dcdf9a.png">

How does EVChargingStation model and properties compare in this regard?

**Comment by albertoabellagarcia** [comment]
I guess that the existing model EVChargingStation refers more to the location where vehicles are charged, its capacity, its main features, etc. And no specifically to the type of entity you are commenting on. So we would be happy if you can PR a new entity for these data. something like OCPIsocket (or similar).

**Comment by albertoabellagarcia** [comment]
Glad to receive your contribution as PR.
