### ISSUE TITLE
Road data model: NGSI-LD normalized example for refRoadSegment incorrect?

### ISSUE THREAD

**Issue by Blobonat** [smart-data-models/dataModel.Transportation#16]
In the NGSI-LD normalized example for a [Road](https://github.com/smart-data-models/dataModel.Transportation/blob/master/Road/examples/example.jsonld) (also the file names are mixed up between key-value and normalized examples) the `refRoadSegment` is given as:

```
"refRoadSegment": {
        "type": "Relationship",
        "object": [
            "urn:ngsi-ld:RoadSegment:Spain-RoadSegment-A62-0-355-forwards",
            "urn:ngsi-ld:RoadSegment:Spain-RoadSegment-A62-0-355-backwards"
        ]
    }
```

As far as I understood the NGSI-LD spec arrays of Relationships do not exist. Since `refRoadSegment` is defined as a Relationship the example seems to be incorrect. 
Shouldn't it use the `datasetId` as mentioned in the [spec in section 4.5.9](https://www.etsi.org/deliver/etsi_gs/CIM/001_099/009/01.04.01_60/gs_cim009v010401p.pdf)? In this case it would look like this:

```
"refRoadSegment": [
     {
          type: "Relationship",
          object: "urn:ngsi-ld:RoadSegment:Spain-RoadSegment-A62-0-355-forwards",
          datasetId: "urn:ngsi-ld:Relationship:Spain-RoadSegment-A62-0-355-forwards"
     },
    {
          type: "Relationship",
          object: "urn:ngsi-ld:RoadSegment:Spain-RoadSegment-A62-0-355-backwards",
          datasetId: "urn:ngsi-ld:Relationship:Spain-RoadSegment-A62-0-355-backwards"
     }
    ]
```

**Comment by albertoabellagarcia** [comment]
that is simply right, we have corrected it.
