### ISSUE TITLE
CityWork model.yaml does not include location attribute

### ISSUE THREAD

**Issue by Blobonat** [smart-data-models/dataModel.Transportation#18]
The `CityWork` data model defines `location` as required, but the [model.yaml](https://github.com/smart-data-models/dataModel.Transportation/blob/master/CityWork/model.yaml) does not include such attribute. I think there was an error while generating the yaml-file, because the `schema.json` correctly includes `https://smart-data-models.github.io/data-models/common-schema.json#/definitions/GSMA-Commons` and `https://smart-data-models.github.io/data-models/common-schema.json#/definitions/Location-Commons/properties`.

**Comment by albertoabellagarcia** [comment]
You are right. Fixed
