### ISSUE TITLE
CityWork model.yaml misses "Geoproperty" type in x-ngsi 

### ISSUE THREAD

**Issue by isalvadori** [smart-data-models/dataModel.Transportation#19]
Hi, 
   in the geo-properties defined in the CityWork model.yaml (`lineLocation` in `busImpacted` for example) a x-ngsi type information, which indicates they are a geo property is missing.
Would it be possible to add it? In other model this is always present when we are dealing with GeoJSON, and it's helpful to quickly extract information about the model structure.

Thanks!

**Comment by albertoabellagarcia** [comment]
There are several points here. On one hand, there were poorly defined descriptions. Now we have changed them and republished identifying properly what attributes were geoproperties. In some minutes it is fixed and available. But, if what you need is the x-ngsi type for subattributes. this is something that we have not currently implemented. It is on the queue anyway but there is not a clear schedule for it. Is the correction good enough or do you need the NGSI type for subattributes?

**Comment by isalvadori** [comment]
Thanks!
I think I can make it work also looking at the description to discriminate what is a geoproperty and what is not. 
But it would be nice to have in the future also the NGSI type for subattributes, indeed.

Thanks again!
