### ISSUE TITLE
Request for addition of value in Enum "VehicleType"

### ISSUE THREAD

**Issue by manurag1234** [smart-data-models/dataModel.Transportation#25]
Hi Team,

Can we please add "pedestrian" in the enum array for VehicleType in Transportation datamodel ?

**Comment by albertoabellagarcia** [comment]
Transportation is not a data model but the name of the subject. Do you mean [vehicle](https://github.com/smart-data-models/dataModel.Transportation/blob/master/Vehicle/schema.json) or [transportStation](https://github.com/smart-data-models/dataModel.Transportation/blob/master/TransportStation/schema.json)?

**Comment by albertoabellagarcia** [comment]
if you need further clarification do it in this thread or just book a support [session](https://calendly.com/smartdatamodels).

**Comment by albertoabellagarcia** [comment]
when you clarify we will be glad to extend the model. Reopen the issue. closing now.
