### ISSUE TITLE
Speed -1 should be allowed for Vehicle

### ISSUE THREAD

**Issue by Glagnar** [smart-data-models/dataModel.Transportation#3]
According to the documentation -1 is valid speed, if speed is unknown.
The schema validation fails if speed is -1

**Comment by albertoabellagarcia** [comment]
This would be the solution, isn't it?
"speed": {
          "oneOf": [
            {
              "type": "number",
              "minimum": 0,
            },
            {
              "type": "number",
              "const": -1
            }
          ]

**Comment by Glagnar** [comment]
@albertoabellagarcia That seems just fint. Cheers.

**Comment by albertoabellagarcia** [comment]
by the end I did it a bit different to have a -1 number. I thought that data type could matter, therefore There is an alternative https://github.com/smart-data-models/dataModel.Transportation/blob/master/Vehicle/schema.json. See it.
