### ISSUE TITLE
Update the enum list of vehicleType attribute

### ISSUE THREAD

**Issue by jaimeventura** [smart-data-models/dataModel.Transportation#4]
According to the datamodel's [documentation](https://github.com/FIWARE/data-models/blob/master/specs/Transportation/Vehicle/Vehicle/doc/spec.md), the vehicleType attribute allows values defined by VehicleTypeEnum a  [DATEX 2 version 2.3](http://d2docs.ndwcloud.nu/_static/umlmodel/v2.3/index.htm?goto=2:3:6:320).

But not all the vehicle types in DATEX 2 version 2.3 are allowed on `vehicleType` attribute. Only a subset is allowed. This is even enforced in the [schema.json](https://github.com/FIWARE/data-models/blob/97ba88ed96907813597fa043fc0155842cad67f4/specs/Transportation/Vehicle/Vehicle/schema.json#L25). For instance `twoWheeledVehicle` (a simple scooter, i believe) is not there.

So, im asking to update this.
I volunteer to work on this and issue a pull request, if there's an agreement in the update of such list.

**Comment by albertoabellagarcia** [comment]
I do think so it is required to meet this documentation, please could you do a PR with this change?
Thanks
